apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postfix
  name: postfix
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postfix
    spec:
      containers:
      - env:
        - name: SERVER_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: SERVER_HOSTNAME
              name: postfix-postfixenv
        - name: SMTP_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SMTP_PASSWORD
              name: postfix-postfixenv
        - name: SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              key: SMTP_SERVER
              name: postfix-postfixenv
        - name: SMTP_USERNAME
          valueFrom:
            configMapKeyRef:
              key: SMTP_USERNAME
              name: postfix-postfixenv
        image: juanluisbaptiste/postfix
        name: postfix
        ports:
        - containerPort: 25
        resources: {}
      restartPolicy: Always
status: {}
