apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: postfix
  name: postfix
spec:
  ports:
  - name: "25"
    port: 25
    targetPort: 25
  selector:
    io.kompose.service: postfix
status:
  loadBalancer: {}
